controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x:      1.5 # 0.5
  min_vel_x:      0.1 # 0.01 # original Udacity value = -0.1 (negative !?)
  max_vel_theta:  1.57 #1.5

  min_in_place_vel_theta: 0.261799 # 15 degress # 18 degrees=0.314

  acc_lim_theta: 3.14
  acc_lim_x: 2.0
  acc_lim_y: 2.0

  sim_time: 1.0 # original Udacity value, but...
  # http://kaiyuzheng.me/documents/navguide.pdf recommendations bellow:
  # sim_time: 2.0 # low value, limited performance, difficulties to pass narrow spaces
  # sim_time: 4.0 # 2.0 # 4.0 # 1.0 # time interval for DWA planner. 4.0 = typical value
  # sim_time: 5.0 # long curver, not very flexible, heavier computational load  

  vx_samples:      5.0 # original Udacity value=5.0
  vtheta_samples: 10.0

  pdist_scale:   0.6 #0.6
  gdist_scale:   0.8 #0.8
  occdist_scale: 0.02

  holonomic_robot: false
